package recyclapp.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Point;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.Border;
import recyclapp.controller.RecyclAppViewController;
import recyclapp.controller.RecyclAppViewController.TypeEquipement;

/**
 *
 * @author mblanchet
 */
public class frmRecyclApp extends javax.swing.JFrame
{
    private TypeEquipement m_typeEquipCourant; 
    private RecyclAppViewController m_controller;

    /**
     * Creates new form frmRecyclApp
     */
    public frmRecyclApp()
    {   
        initComponents();
        
        m_typeEquipCourant = null;
        m_controller = new RecyclAppViewController();
        drawingPanel.SetController(m_controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrpFruit = new javax.swing.ButtonGroup();
        pnlMain = new javax.swing.JPanel();
        pnlToolBar = new javax.swing.JPanel();
        tbtnEntree = new javax.swing.JToggleButton();
        tbtnSortie = new javax.swing.JToggleButton();
        tbtnJonction = new javax.swing.JToggleButton();
        tbtnStation = new javax.swing.JToggleButton();
        scrPMain = new javax.swing.JScrollPane();
        drawingPanel = new recyclapp.gui.DrawingPanel();
        sliZoom = new javax.swing.JSlider();
        lblZoom = new javax.swing.JLabel();
        mainMenu = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuFile_Open = new javax.swing.JMenuItem();
        jMGrille = new javax.swing.JMenuItem();
        mnuFile_Quit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RecyclApp");
        setBackground(new java.awt.Color(204, 0, 51));
        setName("frmRecyclApp"); // NOI18N

        pnlMain.setName(""); // NOI18N
        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlToolBar.setPreferredSize(new java.awt.Dimension(800, 35));
        pnlToolBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        bgrpFruit.add(tbtnEntree);
        tbtnEntree.setText("Entrée Usine");
        tbtnEntree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnEntreeActionPerformed(evt);
            }
        });
        pnlToolBar.add(tbtnEntree);

        bgrpFruit.add(tbtnSortie);
        tbtnSortie.setText("Sortie Usine");
        tbtnSortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnSortieActionPerformed(evt);
            }
        });
        pnlToolBar.add(tbtnSortie);

        bgrpFruit.add(tbtnJonction);
        tbtnJonction.setText("Jonction");
        tbtnJonction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnJonctionActionPerformed(evt);
            }
        });
        pnlToolBar.add(tbtnJonction);

        bgrpFruit.add(tbtnStation);
        tbtnStation.setText("Station");
        tbtnStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnStationActionPerformed(evt);
            }
        });
        pnlToolBar.add(tbtnStation);

        pnlMain.add(pnlToolBar, java.awt.BorderLayout.NORTH);

        drawingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drawingPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drawingPanelMousePressed(evt);
            }
        });

        sliZoom.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliZoomStateChanged(evt);
            }
        });

        lblZoom.setText("Zoom (cm:m)");

        javax.swing.GroupLayout drawingPanelLayout = new javax.swing.GroupLayout(drawingPanel);
        drawingPanel.setLayout(drawingPanelLayout);
        drawingPanelLayout.setHorizontalGroup(
            drawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drawingPanelLayout.createSequentialGroup()
                .addContainerGap(541, Short.MAX_VALUE)
                .addComponent(lblZoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        drawingPanelLayout.setVerticalGroup(
            drawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drawingPanelLayout.createSequentialGroup()
                .addGroup(drawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliZoom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZoom, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 515, Short.MAX_VALUE))
        );

        scrPMain.setViewportView(drawingPanel);

        pnlMain.add(scrPMain, java.awt.BorderLayout.CENTER);

        mnuFile.setText("Fichier");

        mnuFile_Open.setText("Ouvrir");
        mnuFile.add(mnuFile_Open);

        jMGrille.setText("Grille");
        jMGrille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGrilleActionPerformed(evt);
            }
        });
        mnuFile.add(jMGrille);

        mnuFile_Quit.setText("Quitter");
        mnuFile_Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFile_QuitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFile_Quit);

        mainMenu.add(mnuFile);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuFile_QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFile_QuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuFile_QuitActionPerformed

    private void tbtnEntreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnEntreeActionPerformed
        setTypeEquip(TypeEquipement.EntreeUsine);
    }//GEN-LAST:event_tbtnEntreeActionPerformed

    private void tbtnSortieActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbtnSortieActionPerformed
    {//GEN-HEADEREND:event_tbtnSortieActionPerformed
        setTypeEquip(TypeEquipement.SortieUsine);
    }//GEN-LAST:event_tbtnSortieActionPerformed

    private void drawingPanelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_drawingPanelMouseClicked
    {//GEN-HEADEREND:event_drawingPanelMouseClicked
        Point mousePoint = evt.getPoint();    
        
        if (!m_controller.clickUtilisateur(mousePoint)) // l'utilisateur n'a pas cliqué sur un équipement
        {
            // ajout d'un équrement sur le plan
            if (m_typeEquipCourant == null)
                return;

            // TO DO : envoie de bon paramètres pour les dimensions
            Dimension defaultDim = new Dimension(50, 50);
            m_controller.ajouterEquipement(m_typeEquipCourant, mousePoint, defaultDim);
        }
        drawingPanel.repaint();
    }//GEN-LAST:event_drawingPanelMouseClicked

    private void drawingPanelMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_drawingPanelMousePressed
    {//GEN-HEADEREND:event_drawingPanelMousePressed
        if (m_typeEquipCourant == null)    
            return;        
        
        // TO DO : envoie de bon paramètres
        Dimension defaultDim = new Dimension(50, 50);
        Point mousePoint = evt.getPoint();
        m_controller.ajouterEquipement(m_typeEquipCourant, mousePoint, defaultDim);
        drawingPanel.repaint();
    }//GEN-LAST:event_drawingPanelMousePressed

    private void tbtnJonctionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbtnJonctionActionPerformed
    {//GEN-HEADEREND:event_tbtnJonctionActionPerformed
        setTypeEquip(TypeEquipement.Jonction);
    }//GEN-LAST:event_tbtnJonctionActionPerformed

    private void tbtnStationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbtnStationActionPerformed
    {//GEN-HEADEREND:event_tbtnStationActionPerformed
        setTypeEquip(TypeEquipement.Station);
    }//GEN-LAST:event_tbtnStationActionPerformed

    private void jMGrilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGrilleActionPerformed
        // TODO add your handling code here:
        m_controller.drawGrid();
        drawingPanel.repaint();
    }//GEN-LAST:event_jMGrilleActionPerformed

    private void sliZoomStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliZoomStateChanged
        int scale;
        scale = sliZoom.getValue();
        m_controller.setScale(scale);
        drawingPanel.repaint();
    }//GEN-LAST:event_sliZoomStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmRecyclApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmRecyclApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmRecyclApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmRecyclApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new frmRecyclApp().setVisible(true);
            }
        });
    }
    
    public void setTypeEquip(TypeEquipement type) 
    {
        this.m_typeEquipCourant = type;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrpFruit;
    private recyclapp.gui.DrawingPanel drawingPanel;
    private javax.swing.JMenuItem jMGrille;
    private javax.swing.JLabel lblZoom;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuFile_Open;
    private javax.swing.JMenuItem mnuFile_Quit;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlToolBar;
    private javax.swing.JScrollPane scrPMain;
    private javax.swing.JSlider sliZoom;
    private javax.swing.JToggleButton tbtnEntree;
    private javax.swing.JToggleButton tbtnJonction;
    private javax.swing.JToggleButton tbtnSortie;
    private javax.swing.JToggleButton tbtnStation;
    // End of variables declaration//GEN-END:variables
}
